#pragma config(Motor,  port2,           frightdrive,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           fleftdrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           brightdrive,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           bleftdrive,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

 while(1==1) // = x=1 set equal
             // ==   x==1 comparing
 {

   motor[bleftdrive] = vexRT(Btn5U)*127 - vexRT(Btn5D)*127;
   motor[fleftdrive] = vexRT(Ch3);
   motor[frightdrive] = vexRT(Ch2Xmtr2);
   motor[brightdrive] = vexRT(Ch2);


 }


}
